### ISSUE TITLE
put command fails when bashrc contains a cd

### ISSUE THREAD

**Issue by gingerlime** [ploxiln/fab-classic#34]
Nice to see fab-classic ! I didn't know it exists until now.

I have a question that I hope someone can help with. I noticed that my `put` commands fail if my `.bashrc` contains a `cd` command ... in my case, I'm sourcing another file from my `.bashrc` and at the end of this file I do a `cd /my/folder`. This works totally fine, but then if I try to run a `put("something", "/remote/folder/xyz")`, it always fails with 

```
[root@1.2.3.4] put: /my/local/file -> /my/remote/file

Fatal error: sudo() received nonzero return code 1 while executing!

Requested: mv "3bfff637b1dc4ccabd86becf6542a3d6" "/my/remote/file"
Executed: sudo -S -p 'sudo password:'  /bin/bash -l -c "mv \"3bfff637b1dc4ccabd86becf6542a3d6\" \"/my/remote/file\""
```

I know I can probably remove the `cd` from my `.bashrc`, but is there another way around it?

I even try to only source the file if it's not a tty, e.g. `tty -s && source .my_rc_file`, but it is still sourced with fabric.

**Comment by ploxiln** [comment]
This looks like an issue with `put()` and `use_sudo=True` mode (where it does a plain put to a temporary file first, then uses `sudo()` to move it to the final location, and `sudo()` by default uses a pty/tty). Can you `put()` *without* `use_sudo` (and without wrapping in sudo context), and then maybe you can use a more custom `run()` or `sudo()` to move it to the final location which it seems you needed sudo for?

**Comment by gingerlime** [comment]
Thanks for getting back so quickly and for the suggestion. I’ll give it a try. I’m wondering if the latter option hints at a potential fix that would make put with sudo more robust? eg always put into /tmp or something rather than current folder? (So fabric knows where to mv from). Or grab the local folder and use it later inside the sudo mv ?

**Comment by ploxiln** [comment]
There is a `temp_dir` kwarg for `put()` (which defaults to blank, but you could set it to "/tmp").

**Comment by gingerlime** [comment]
Thanks again @ploxiln. That's good to know! I still wonder if changing the defaults would make it more robust in similar situations (perhaps those are rare though, I don't know).

**Comment by gingerlime** [comment]
I guess in this line, making sure that the full path is captured, even if temp_dir isn't specified?

https://github.com/ploxiln/fab-classic/blob/eb0b3cddee984a0729ec34c94ec1f4ea4a9cd1ed/fabric/sftp.py#L245

**Comment by ploxiln** [comment]
Yeah, that may be possible. Another idea that would have avoided your particular case is for fabric.sftp to call `sudo()` with `pty=False`.

**Comment by gingerlime** [comment]
I'm not sure what the implications of using sudo with pty=False, but I guess for the purpose of copying stuff over, it should be safe? 

somehow intuitively making sure that we get the full path of the temp file, so we can definitely know where to copy it from, seems more robust? (I'm really just guessing, I don't know the fabric codebase at all).

**Comment by gingerlime** [comment]
... unless the sftp folder structure is different from the real one? or the one that you get via ssh? (e.g. I think some setups might chroot your ftp access or something...?)
